# Generated by Django 4.2 on 2023-05-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='login.equipe'),
        ),
        migrations.AlterModelTable(
            name='technician',
            table=None,
        ),
    ]
