# Generated by Django 4.2 on 2023-05-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_specialite_technician'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='specialite',
            table='specialite',
        ),
        migrations.AlterModelTable(
            name='technician',
            table='technician',
        ),
    ]
