# Generated by Django 4.2 on 2023-05-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_technician_equipe_alter_technician_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipe',
            table='Equipe',
        ),
        migrations.AlterModelTable(
            name='technician',
            table='Technician',
        ),
    ]
