# Generated by Django 4.2 on 2023-05-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_equipe_table_alter_technician_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipe',
            table='equipe',
        ),
        migrations.AlterModelTable(
            name='technician',
            table='technician',
        ),
    ]
