# Generated by Django 4.2 on 2023-05-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_equipe_table_alter_technician_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='equipes', to='login.technician'),
        ),
    ]
