# Generated by Django 4.2 on 2023-05-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_equipe_technicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='login.equipe', unique=True),
        ),
    ]
